### PR TITLE
35c3 Slide

### PR DESCRIPTION
**Pull request by dbrgn**
Also moves FOSDEM slides to subdir.

### CODE REVIEW

**Comment by ubruhin** [comment]
Thanks! 

To be honest, I'm not sure if it's a good idea to name the subdirectories according where the slides are shown (e.g. FOSDEM or 35C3). These directories contain nothing specific to these events. What if the same slides are shown at a different event, would we need to duplicate the whole directory? Also the whole LaTeX project is not reusable that way, thus old presentations will never get updates - I intended to reuse the slides and basically only adjust the main *.tex to include the slides which are needed for a specific presentation. I already used Git Tags to keep in mind which revision was used for a specific event, and uploaded the corresponding PDF to GitHub Releases.

So I would rather add the `logo.svg` to the `images` directory, and the `librepcb-slide.svg` to a new subdirectory called `misc` or so. Then add a Tag `2018.12.27-35c3` and upload the `v1.png` to GitHub Releases.

**Comment by dbrgn** [comment]
Done

**Review by ubruhin — APPROVED** [review]
:+1:

**Comment by dbrgn** [comment]
@ubruhin you'll have to merge, tag & release.

img

**Comment by ubruhin** [comment]
Done -> https://github.com/LibrePCB/librepcb-slides/releases/tag/2018.12.27-35c3

**Pull request merged**
